import { ClassYearGroup } from './types';

export const classYears: ClassYearGroup = {
    '2024': [
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
    ],
    '2025': [
      {
        name: "Liam Kronman",
        hometown: "New York, NY",
        instagram: "liamkronman",
        interests: ["Soccer", "Golf", "Music"],
        photoUrl: "https://i.imgur.com/5Z3Z5ZM.jpg",
      },
      {
        name: "Oliver Martinez",
        hometown: "Miami, FL",
        instagram: "olivermtz",
        interests: ["Cooking", "Travel", "Languages"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
    ],
    '2026': [
      {
        name: "William Johnson",
        hometown: "Austin, TX",
        instagram: "willjohnson",
        interests: ["Gaming", "Skateboarding", "Vlogging"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "James Davis",
        hometown: "Seattle, WA",
        instagram: "jamesdavis",
        interests: ["Robotics", "Snowboarding", "Painting"],
        photoUrl: "https://i.imgur.com/5Z3Z5ZM.jpg",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
    ],
    '2027': [
      {
        name: "Benjamin Lee",
        hometown: "Denver, CO",
        instagram: "benlee",
        interests: ["Martial Arts", "Astronomy", "Guitar"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Lucas Hernandez",
        hometown: "San Francisco, CA",
        instagram: "lucashernandez",
        interests: ["Surfing", "Startups", "Blogging"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
      {
        name: "Ethan Walker",
        hometown: "Los Angeles, CA",
        instagram: "ethanwalker",
        interests: ["Photography", "Technology", "Hiking"],
        photoUrl: "https://i.imgur.com/LpaY82x.png",
      },
      {
        name: "Noah Smith",
        hometown: "Chicago, IL",
        instagram: "noahsmith",
        interests: ["Basketball", "Reading", "Coding"],
        photoUrl: "https://i.imgur.com/DlK5hz6.png",
      },
    ],
};